{
    "DWF": {
        "references": [
            "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2021-32027",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1956876"
        ]
    },
    "MITRE": {
        "CVE_data_meta": {
            "ASSIGNER": "secalert@redhat.com",
            "ID": "CVE-2021-32027",
            "STATE": "PUBLIC"
        },
        "affects": {
            "vendor": {
                "vendor_data": [
                    {
                        "product": {
                            "product_data": [
                                {
                                    "product_name": "postgresql",
                                    "version": {
                                        "version_data": [
                                            {
                                                "version_value": "postgresql 13.3, postgresql 12.7, postgresql 11.12, postgresql 10.17, postgresql 9.6.22"
                                            }
                                        ]
                                    }
                                }
                            ]
                        },
                        "vendor_name": "n/a"
                    }
                ]
            }
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [
                {
                    "lang": "eng",
                    "value": "A flaw was found in postgresql in versions before 13.3, before 12.7, before 11.12, before 10.17 and before 9.6.22. While modifying certain SQL array values, missing bounds checks let authenticated database users write arbitrary bytes to a wide area of server memory. The highest threat from this vulnerability is to data confidentiality and integrity as well as system availability."
                }
            ]
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "eng",
                            "value": "CWE-190->CWE-119"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1956876",
                    "refsource": "MISC",
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1956876"
                },
                {
                    "name": "https://www.postgresql.org/support/security/CVE-2021-32027/",
                    "refsource": "MISC",
                    "url": "https://www.postgresql.org/support/security/CVE-2021-32027/"
                }
            ]
        }
    },
    "NVD": {
        "configurations": {
            "CVE_data_version": "4.0",
            "nodes": []
        },
        "cve": {
            "CVE_data_meta": {
                "ASSIGNER": "secalert@redhat.com",
                "ID": "CVE-2021-32027"
            },
            "data_format": "MITRE",
            "data_type": "CVE",
            "data_version": "4.0",
            "description": {
                "description_data": [
                    {
                        "lang": "en",
                        "value": "A flaw was found in postgresql in versions before 13.3, before 12.7, before 11.12, before 10.17 and before 9.6.22. While modifying certain SQL array values, missing bounds checks let authenticated database users write arbitrary bytes to a wide area of server memory. The highest threat from this vulnerability is to data confidentiality and integrity as well as system availability."
                    }
                ]
            },
            "problemtype": {
                "problemtype_data": [
                    {
                        "description": []
                    }
                ]
            },
            "references": {
                "reference_data": [
                    {
                        "name": "https://www.postgresql.org/support/security/CVE-2021-32027/",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://www.postgresql.org/support/security/CVE-2021-32027/"
                    },
                    {
                        "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1956876",
                        "refsource": "MISC",
                        "tags": [],
                        "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1956876"
                    }
                ]
            }
        },
        "impact": {},
        "lastModifiedDate": "2021-06-01T14:32Z",
        "publishedDate": "2021-06-01T14:15Z"
    }
}